#!/usr/bin/env python

import sys
args = sys.argv    

MAX = int(args[args.index("--max")+1])
MIN = int(args[args.index("--min")+1])

out = sys.stdout
err = sys.stderr
fa = sys.stdin

for line in fa:
    if ">" in line:
        curr = str(line)
    else:
        mline = line.rstrip().upper()
        G = mline.count('G')
        C = mline.count('C')
        GC = (G+C)/len(mline) *100

        if GC > MIN and GC < MAX:
            out.write(curr+line.upper())
            err.write("Done! Sequence has processed.\n")
        else:
            err.write('Warrning! GC-COMPOSITION DOES NOT BELONG TO THE RANGE.\n')
